<cfquery name="getc" datasource="#dsn#">
    select TOP 100 NICKNAME,C.COMPANY_ID,TT.* from workcube_metosan.COMPANY as C
OUTER APPLY(
    SELECT SUM(ISNULL(BR,0)) ALACAK,SUM(ISNULL(AR,0)) BORC,CONVERT(DECIMAL(18,2),SUM(ISNULL(AR,0)-ISNULL(BR,0))) AS BAKIYE,
CASE WHEN SUM(ISNULL(BR,0))>SUM(ISNULL(AR,0)) THEN 'A' ELSE 'B' END AS BA
 FROM (
SELECT 
ISNULL(FROM_CMP_ID,TO_CMP_ID) CMP,
CASE WHEN FROM_CMP_ID IS NOT NULL THEN SUM(ACTION_VALUE) END AS BR,
CASE WHEN TO_CMP_ID IS NOT NULL THEN SUM(ACTION_VALUE) END AS AR

 FROM workcube_metosan_2024_1.CARI_ROWS WHERE FROM_CMP_ID=C.COMPANY_ID OR TO_CMP_ID=C.COMPANY_ID
 GROUP BY FROM_CMP_ID,TO_CMP_ID

) AS TF
) AS TT 
where COMPANY_ID=13205
</cfquery>

<cfdump var="#getc#">



<cfoutput query="getc">
    <CFSET AF_TUTAR=0>
<cfquery name="GETAF" datasource="#DSN2#">
    SELECT * FROM CARI_ROWS WHERE FROM_CMP_ID=#COMPANY_ID# ORDER BY ACTION_DATE
</cfquery>
<CFSET SIRA=1>
<cfquery name="GETSF" datasource="#DSN2#">
    SELECT TOP 10 * FROM CARI_ROWS WHERE TO_CMP_ID=#COMPANY_ID# ORDER BY ACTION_DATE
</cfquery>
<CFSET AF_TUTAR=AF_TUTAR+GETAF.ACTION_VALUE[SIRA]>


<cfloop query="GETSF">
    <CFSET KAPANAN=AF_TUTAR-ACTION_VALUE>
    #AF_TUTAR# -- #ACTION_VALUE# ---- #KAPANAN#<BR>
   <CFIF KAPANAN GT 0>
    <CFSET AF_TUTAR=KAPANAN>
   <CFELSE>
    <CFSET SIRA=SIRA+1>
    <cfbreak>
   </CFIF>


</cfloop>



</cfoutput>