<cfquery name="getPor" datasource="#dsn3#">
    SELECT * FROM PBS_OFFER_ROW AS POR 
        LEFT JOIN PBS_OFFER AS PO PO.OFFER_ID=POR.OFFER_ID
        LEFT JOIN COMPANY AS C ON C.COMPANY_ID=POR.COMPANY_ID
        LEFT JOIN EMPLOYEES AS EMP ON EMP.EMPLOYEE_ID=PO.RECORD_EMP
        
</cfquery>