CREATE TABLE [workcube_metosan_1].[VIRTUAL_PRODUCTION_ORDERS](
	[V_P_ORDER_ID] [int] IDENTITY(1,1) NOT NULL,
	[P_ORDER_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[IS_FROM_VIRTUAL] [bit] NULL,
	[P_ORDER_STATUS] [bit] NULL,
	[OFFER_ROW_ID] [int] NULL,
	[QUANTITY] [float] NULL,
	[UNIQUE_RELATION_ID] [nvarchar](150) NULL,
	[V_P_ORDER_NO] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[V_P_ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [workcube_metosan]
GO

/****** Object:  Table [workcube_metosan_1].[VIRTUAL_PRODUCTION_ORDERS_STOCKS]    Script Date: 11/29/2022 3:54:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [workcube_metosan_1].[VIRTUAL_PRODUCTION_ORDERS_STOCKS](
	[V_P_ORDER_STOCK_ID] [int] IDENTITY(1,1) NOT NULL,
	[V_P_ORDER_ID] [int] NULL,
	[STOCK_ID] [int] NULL,
	[AMOUNT] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[V_P_ORDER_STOCK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


/*





*/