<cfquery name="getsTree" datasource="#dsn3#">
    SELECT S.PRODUCT_NAME,S.STOCK_CODE,S.STOCK_ID,S.PRODUCT_ID,VPT.AMOUNT,VPQ.QUESTION,PU.MAIN_UNIT,VP_ID,VPQ.QUESTION_ID,S.BARCOD,VPT.PRICE,VPT.DISCOUNT,VPT.MONEY FROM #dsn3#.VIRTUAL_PRODUCT_TREE_PRT AS VPT
LEFT JOIN #dsn3#.STOCKS AS S ON VPT.STOCK_ID=S.STOCK_ID
LEFT JOIN #dsn3#.VIRTUAL_PRODUCT_TREE_QUESTIONS AS VPQ ON VPQ.QUESTION_ID=VPT.QUESTION_ID
LEFT JOIN #dsn3#.PRODUCT_UNIT AS PU ON PU.PRODUCT_ID=S.PRODUCT_ID AND PRODUCT_UNIT_STATUS=1
WHERE  VP_ID=#getPo.STOCK_ID#
ORDER BY VP_ID  
</cfquery>
<cfdump var="#getsTree#">